### ISSUE TITLE
Error: undefined method `id' for #<KillBillClient::Model::OverdueStateConfig:0x007fd718de31a8>

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#113]
Upgrading to Rails 5 broke the `new_overdue_config` screen because of https://github.com/rails/rails/commit/7089768b700f79b2ae5171dc434ef45d16d18a63 (see [this](https://github.com/killbill/killbill-admin-ui/blob/30c60ef14925a1d2e6c3aa63b75589f258f310d9/app/views/kaui/admin_tenants/new_overdue_config.html.erb#L32)).

It looks like we either need to change how we invoke `fields_for` or maybe switch to `form_tag`.
